hotel/about/urls.py
from django.urls import path
from . import views

app_name='about'

urlpatterns = [
    path('', views.about_us, name='about_us'),
]

hotel/agent/urls.py
from django.urls import path
from . import views

app_name='agent'

urlpatterns = [
    path('', views.agents_list, name='agents_list'),
]

hotel/contact/urls.py
from django.urls import path
from . import views

app_name='contact'

urlpatterns = [
    path('', views.contact, name='contact'),
]

hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('property.urls', namespace='property')),
    path('agents/', include('agent.urls', namespace='agent')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/property/urls.py
from django.urls import path
from . import views

app_name='property'

urlpatterns = [
    path('', views.property_list, name='property_list'),
    path('<int:id>', views.property_detail, name='property_detail'),
]

hotel/about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    vision=models.TextField()
    mission=models.TextField()
    image=models.ImageField(upload_to='about', null=True)

    def __str__(self):
        return str(self.id)

hotel/agent/models.py
from django.db import models


# Create your models here.
class Agent(models.Model):
    name=models.CharField(max_length=50)
    title=models.CharField(max_length=50)
    image=models.ImageField(upload_to='agents', null=True)

    def __str__(self):
        return self.name

hotel/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    pass

hotel/property/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Category'
        verbose_name_plural='Categories'


PROPERTY_TYPE=(
    ('S', 'sale'),
    ('R', 'rent')
)

class Property(models.Model):
    name=models.CharField(max_length=50)
    property_type=models.CharField(choices=PROPERTY_TYPE, max_length=10)
    price=models.PositiveIntegerField()
    category=models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    area=models.DecimalField(decimal_places=2, max_digits=5)
    beds_number=models.PositiveIntegerField()
    baths_number=models.PositiveIntegerField()
    garages_number=models.PositiveIntegerField()
    image=models.ImageField(upload_to='properties', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Property'
        verbose_name_plural='Properties'


class Reserve(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    notes=models.TextField()

    def __str__(self):
        return self.name

hotel/property/forms.py
from django import forms
from .models import Reserve


class ReserveForm(forms.ModelForm):
    class Meta:
        model=Reserve
        fields='__all__'

hotel/about/views.py
from django.shortcuts import render
from .models import About


# Create your views here.
def about_us(request):
    about=About.objects.last()
    return render(request, 'about_us.html', {'about':about})

hotel/agent/views.py
from django.shortcuts import render
from .models import Agent


# Create your views here.
def agents_list(request):
    agents_list=Agent.objects.all()
    return render(request, 'agents.html', {'agents_list':agents_list})

hotel/contact/views.py
from django.shortcuts import render
from .models import Contact


# Create your views here.
def contact(request):
    contact=Contact.objects.last()
    return render(request, 'contact.html', {'contact':contact})

hotel/property/views.py
from django.shortcuts import render
from .models import Property, Category
from .forms import ReserveForm


# Create your views here.
def property_list(request):
    property_list=Property.objects.all()
    return render(request, 'list.html', {'property_list':property_list})


def property_detail(request, id):
    property=Property.objects.get(pk=id)
    if request.method=='POST':
        reserve_form=ReserveForm(request.POST)
        if reserve_form.is_valid():
            pass
    else:
        reserve_form=ReserveForm()
    context={'property':property, 'reserve_form':reserve_form}
    return render(request, 'detail.html', context)

hotel/about/templates/about_us.html
{% extends 'base.html' %}

{% block content %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>About</span>
              </div>
              <h1>About Us</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <div class="col-md-12"><h2 class="mt0 mb50 text-center">Our Company</h2></div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{about.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h2>Our Mission</h2>
          <p>{{about.mission}}</p>
        </div>
        <div class="col-md-6">
          <h2>Our Vision</h2>
            <p>{{about.vision}}</p>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

hotel/agent/templates/agents.html
{% extends 'base.html' %}

{% block content %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Agents</span>
              </div>
              <h1>Agents</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->
  
  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Agents</h2>
      </div>
      <div class="row">
      {% for agent in agents_list %}
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{{agent.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">{{agent.name}}</h2>
              <p><small>{{agent.title}}</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </section>
{% endblock content %}

hotel/contact/templates/contact.html
{% extends 'base.html' %}

{% block contact %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>About</span>
              </div>
              <h1>Contact</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->
  
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <form action="#" method="post" class="probootstrap-form mb60">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="fname">First Name</label>
                  <input type="text" class="form-control" id="fname" name="fname">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="lname">Last Name</label>
                  <input type="text" class="form-control" id="lname" name="lname">
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="form-group">
              <label for="message">Message</label>
              <textarea cols="30" rows="10" class="form-control" id="message" name="message"></textarea>
            </div>
            <div class="form-group">
              <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Send Message">
            </div>
          </form>
        </div>
        <div class="col-md-3 col-md-push-1">
          <h4>Contact Details</h4>
          <ul class="with-icon colored">
            <li><i class="icon-location2"></i> <span>198 West 21th Street, Suite 721 New York NY 10016</span></li>
            <li><i class="icon-mail"></i><span>info@domain.com</span></li>
            <li><i class="icon-phone2"></i><span>+123 456 7890</span></li>
          </ul>

          <h4>Feedback</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Learn More</a></p>
        </div>
      </div>
    </div>
  </section>  
  <div id="map"></div>
{% endblock contact %}

hotel/property/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>uiCookies:Haus &mdash; Free Bootstrap Theme, Free Responsive Bootstrap Website Template</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
      <script src="{% static 'js/vendor/respond.min.js' %}"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="{% url 'property:property_list' %}" class="probootstrap-logo">Haus<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li class="active"><a href="{% url 'property:property_list' %}">Home</a></li>
            <li><a href="{% url 'property:property_list' %}">Properties</a></li>
            <li><a href="{% url 'agent:agents_list' %}">Agents</a></li>
            <li><a href="{% url 'about:about_us' %}">About</a></li>
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>

  {% block content %}
  {% endblock content %}

  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url(img/slider_3.jpg)">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">About Haus.</h4>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            <p><a href="#">Read more...</a></p>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Quick Links</h4>
            <ul class="stack-link">
              <li><a href="#">Property Listing</a></li>
              <li><a href="#">Rent Properties</a></li>
              <li><a href="#">Sell Properties</a></li>
              <li><a href="#">Agents</a></li>
              <li><a href="#">Testimonial</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Popular Cities</h4>
            <ul class="stack-link">
              <li><a href="#">New York <small>(320 properties)</small></a></li>
              <li><a href="#">San Francisco <small>(294 properties)</small></a></li>
              <li><a href="#">Brooklyn <small>(300 properties)</small></a></li>
              <li><a href="#">Chicago <small>(268 properties)</small></a></li>
              <li><a href="#">Los Angeles <small>(342 properties)</small></a></li>
            </ul>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Subscribe</h4>
            <p>Far far away behind the word mountains far from.</p>
            <form action="#">
              <div class="form-field">
                <input type="text" class="form-control" placeholder="Enter your email">
                <button class="btn btn-subscribe">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2017 <a href="https://uicookies.com/">uiCookies:Haus</a>. Designed by <a href="https://uicookies.com/">uicookies.com</a> <br> Demo Photos from <a href="https://pixabay.com/">Pixabay</a> &amp; <a href="https://unsplash.com/">Unsplash</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  

  <script src="{% static 'js/scripts.min.js' %}"></script>
  <script src="{% static 'js/main.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

hotel/property/templates/detail.html
{% extends 'base.html' %}

{% block content %}

  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'property:property_list' %}">Properties</a>{{property}}</span>
              </div>
              <h1>{{property}}</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Details</h2>
          <p>Type: {{property.category}}</p>
          <p>Area: {{property.area}} mp</p>
          <p>Bedrooms: {{property.beds_number}}</p>
          <p>Baths: {{property.baths_number}}</p>
          <p>Garages: {{property.garages_number}}</p>
          <h4>Price: {{property.price}}$ {% if property.property_type == 'R' %}/month{% endif %} </h4>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Reserve this property</h2>
          <form action="{% url 'property:property_list' %}" method='POST'>
          {% csrf_token %}
          {{reserve_form.as_p}}
          <button type="submit">Reserve</button>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

hotel/property/templates/list.html
{% extends 'base.html' %}

{% block content %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="">Properties</a></span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
      {% for property in property_list %}
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.id %}">{{property.name}}</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>{{property.property_type}}</span></div>
              <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong> 
                                                                {% if property.property_type == 'R' %}/month{% endif %}</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>{{property.area}} m2</span>
                </li>
                <li>
                  Beds
                  <span>{{property.beds_number}}</span>
                </li>
                <li>
                  Baths
                  <span>{{property.baths_number}}</span>
                </li>
                <li>
                  Garages
                  <span>{{property.garages_number}}</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
      {% endfor %}
      </div>
    </div>
  </section>

{% endblock content %}